package upstream

// BuildDirective returns the per-request system directive.  With no tools
// declared it is a plain "answer directly" directive; tool-mode directives
// are generated by the tool-call sidecar (the ported toolforge XYML engine)
// and injected by the server before this item.
func BuildDirective(toolsJSON string) string {
	if toolsJSON != "" {
		return ""
	}
	return `[System Directive]
You are an OpenAI-compatible API assistant. Answer the user's question directly and naturally. Do not mention tools, skills, or your own capabilities unless asked.
---`
}

// InitPrompt returns a minimal session-initialization prompt used when a fresh
// session is created.  It primes the session with the assistant identity and
// the no-native-tools posture without creating any skill files.
func InitPrompt() []ContentItem {
	return []ContentItem{{
		Type: "text",
		Text: "[Session Initialization]\nYou are an OpenAI-compatible API assistant. You answer directly; you never execute tools yourself. Reply with a single word: OK.",
	}}
}
